heartbeat:
  _target_: mlbpestimation.data.decorator.preprocessedloader.PreprocessedLoader
  preprocessing:
    _target_: mlbpestimation.preprocessing.pipelines.heartbeatpreprocessing.HeartbeatPreprocessing
    frequency: ${hypothesis.dataset.source.frequency}
