_target_: mlbpestimation.data.mimic4.mimicdatasetloader.MimicDatasetLoader
mimic_wave_files_directory: ${directories.data}/raw/mimic-IV/physionet.org/files/mimic4wdb/0.1.0/waves
random_seed: ${random_seed}
use_ppg: true
frequency: 125