optimizer:
  _target_: tensorflow.python.keras.optimizer_v2.adam.Adam
  learning_rate: 1e-6
loss:
  _target_: tensorflow.python.keras.losses.MeanSquaredError
batch_size: 20
epoch: 100
validation_split: None
n_batches: None