_target_: mlbpestimation.data.preprocessedloader.PreprocessedLoader
dataset_loader:
  _target_: mlbpestimation.data.uci.ucidatasetloader.UciDatasetLoader
  uci_files_directory: ${directories.data}/uci
  random_seed: ${random_seed}
preprocessing:
  _target_: mlbpestimation.preprocessing.pipelines.windowpreprocessing.WindowPreprocessing
  frequency: 63
