defaults:
  - model: baseline
  - dataset_loader: mimic_window_saved
  - optimization: adam

_target_: mlbpestimation.hypothesis.Hypothesis
output_directory: ${directories.output}
validation_split: 0.15
n_batches: 1000

