_target_: mlbpestimation.data.preprocessedloader.PreprocessedLoader
dataset_loader:
  _target_: mlbpestimation.data.vitaldb.vitaldatasetloader.VitalDatasetLoader
preprocessing:
  _target_: mlbpestimation.preprocessing.pipelines.windowpreprocessing.WindowPreprocessing
  frequency: 500
