_target_: mlbpestimation.models.resnet.ResNet
start_filters: 16
max_filters: 128
first_octave_modules: 10
second_octave_modules: 15
third_octave_modules: 20
fourth_octave_modules: 10
regressor_layers: 2
regressor_units: 32
regressor_dropout: 0.25
regressor_activation: relu
l2_lambda: .001
output_units: 2
use_2d: true
