wandb:
  run_name: $WANDB_RUN_NAME
  project_name: test-project
  entity: warpfive
  mode: $WANDB_RUN_MODE
  config:
    testing: true
data:
  mimic:
    file_location: $MIMIC_FILE_LOCATION
  database:
    url:
      protocol: postgresql
      username: $DATABASE_URL_USERNAME
      password: $DATABASE_URL_PASSWORD
      host: $DATABASE_URL_HOST
      port: 5432
      schema: $DATABASE_URL_SCHEMA