wandb:
  run_name: $WANDB_RUN_NAME
  project_name: test-project
  entity: warpfive
  mode: $WANDB_RUN_MODE
  config:
    testing: true
data:
  mimic:
    file_location: /mnt/mimic4/physionet.org/files/mimic4wdb/0.1.0/waves