random_seed: 106
wandb:
  project_name: ml-bp-estimation
  entity: warpfive
  mode: $WANDB_RUN_MODE
  config:
    testing: true
data:
  directory: $DATA_DIRECTORY_PATH
output:
  models: $MODEL_OUTPUT_DIRECTORY