beatsequence:
  _target_: mlbpestimation.data.decorator.preprocessedloader.PreprocessedLoader
  preprocessing:
    _target_: mlbpestimation.preprocessing.pipelines.beatsequencepreprocessing.BeatSequencePreprocessing
    frequency: ${hypothesis.dataset.source.frequency}
    lowpass_cutoff: 5
    bandpass_cutoff:
      - 0.1
      - 8
    min_pressure: 30
    max_pressure: 230
    beat_length: 50
    sequence_steps: 10
    sequence_stride: 1
