beatseries:
  _target_: mlbpestimation.data.decorator.preprocessedloader.PreprocessedLoader
  training_preprocessing:
    _target_: mlbpestimation.preprocessing.pipelines.beatseries.BeatSeriesPreprocessing
    frequency: ${hypothesis.dataset.source.frequency}
    lowpass_cutoff: 5
    bandpass_cutoff:
      - 0.1
      - 8
    min_pressure: 30
    max_pressure: 230
    beat_length: 100
    sequence_steps: 10
    sequence_stride: 1
    scale_per_signal: true
    bandpass_output: true
  test_preprocessing:
    _target_: mlbpestimation.preprocessing.pipelines.beatseries.BeatSeriesPreprocessing
    frequency: ${hypothesis.dataset.source.frequency}
    lowpass_cutoff: 5
    bandpass_cutoff:
      - 0.1
      - 8
    min_pressure: 30
    max_pressure: 230
    beat_length: 100
    sequence_steps: 10
    sequence_stride: 1
    scale_per_signal: true
    bandpass_output: true
