subsampletrain:
  _target_: mlbpestimation.data.decorator.trainingpipelinepreprocess.TrainingPipelinePreprocess
  pipeline:
    _target_: mlbpestimation.preprocessing.pipelines.shufflesample.ShuffleSample
    sample_rate: 1
    random_seed: ${random_seed}

