subsampletrain:
  _target_: mlbpestimation.data.decorator.preprocessedloader.PreprocessedLoader
  training_preprocessing:
    _target_: mlbpestimation.preprocessing.pipelines.shufflesample.ShuffleSample
    sample_rate: 1
  test_preprocessing:
    _target_: mlbpestimation.preprocessing.base.DatasetPreprocessingPipeline
    dataset_operations:
      - _target_: mlbpestimation.preprocessing.shared.transforms.FlattenDataset
      - _target_: mlbpestimation.preprocessing.base.Shuffle


