window:
  _target_: mlbpestimation.data.decorator.preprocessedloader.PreprocessedLoader
  preprocessing:
    _target_: mlbpestimation.preprocessing.pipelines.windowpreprocessing.WindowPreprocessing
    frequency: ${hypothesis.dataset.source.frequency}
    window_size: 8
    window_step: 2
    min_pressure: 30
    max_pressure: 230
    lowpass_cutoff: 5
    bandpass_cutoff:
      - 0.1
      - 8
    scale_per_signal: false