_target_: mlbpestimation.data.preprocessedloader.PreprocessedLoader
dataset_loader:
  _target_: mlbpestimation.data.mimic4.mimicdatasetloader.MimicDatasetLoader
  mimic_wave_files_directory: ${directories.data}/mimic-IV/physionet.org/files/mimic4wdb/0.1.0/waves
  random_seed: ${random_seed}
preprocessing:
  _target_: mlbpestimation.preprocessing.pipelines.beatsequencepreprocessing.BeatSequencePreprocessing
  frequency: 125
  lowpass_cutoff: 5
  bandpass_cutoff:
    - 0.1
    - 8
  min_pressure: 30
  max_pressure: 230
  beat_length: 100
  sequence_steps: 12
  sequence_stride: 1


