_target_: mlbpestimation.data.preprocessedloader.PreprocessedLoader
dataset_loader:
  _target_: mlbpestimation.data.mimic4.mimicdatasetloader.MimicDatasetLoader
preprocessing:
  _target_: mlbpestimation.preprocessing.pipelines.windowpreprocessing.WindowPreprocessing
  frequency: 63
