defaults:
  - dataset_loader: mimic
  - preprocessing: beatsequence

_target_: mlbpestimation.data.decorator.preprocessedloader.PreprocessedLoader
save_directory: ${data_directory}/mimic-beatsequence
