defaults:
  - base_save_dataset_configuration
  - _self_

dataset:
  _target_: mlbpestimation.data.uci.ucidatasetloader.UciDatasetLoader
  uci_files_directory: ${data_directory}/uci
  random_seed: ${random_seed}
  frequency: 125
save_directory: ${data_directory}/uci-cached
