defaults:
  - base_save_dataset_configuration
  - _self_

dataset:
  _target_: mlbpestimation.data.shufflesplitdatasetloader.ShuffleSplitDatasetLoader
  dataset_loader:
    _target_: mlbpestimation.data.preprocessedloader.PreprocessedLoader
    dataset_loader:
      _target_: mlbpestimation.data.vitaldb.vitaldatasetloader.VitalDatasetLoader
      random_seed: ${random_seed}
    preprocessing:
      _target_: mlbpestimation.preprocessing.pipelines.heartbeatpreprocessing.HeartbeatPreprocessing
      frequency: 500
  train_size: 0.7
  validation_size: 0.15
  test_size: 0.15
save_directory: ${data_directory}/vital-heartbeat-shuffle