_target_: mlbpestimation.models.resnet.ResNet
start_filters: 64
max_filters: 256
first_octave_modules: 2
second_octave_modules: 4
third_octave_modules: 8
fourth_octave_modules: 2
regressor_layers: 2
regressor_units: 128
regressor_dropout: 0.01
regressor_activation: relu
l2_lambda: .001
output_units: 2
use_2d: true
