_target_: mlbpestimation.models.transformerencoder.TransformerEncoder
n_encoder_modules: 2
n_attention_heads: 7
d_embedding: 50
attention_dropout: 0.0
ff_encoder_units: 128
ff_encoder_dropout: 0.0
n_regressor_layers: 3
regressor_units: 4096
output_units: 2
regressor_dropout: 0.0